# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-pkgnew-pj2" do
  version "4.0.0"

  on_arm do
    sha256 "15cac96ed8ff798c09399ebcfb474bdde28ee2a1b5a59c6e15c8d8eaf71cc3cb"
    url "https://github.com/naga-nandyala/pj2/releases/download/v4.0.0/mycli-4.0.0-macos-arm64.pkg"
  end

  on_intel do
    sha256 "8a4ae5cd74360d68e574432ceccf9a5d746f9e6901be0395a2b68d5d1998f8d2"
    url "https://github.com/naga-nandyala/pj2/releases/download/v4.0.0/mycli-4.0.0-macos-x86_64.pkg"
  end

  name "MyCLI App (PKG Installer)"
  desc "Azure-inspired CLI with native macOS installer"
  homepage "https://github.com/naga-nandyala/pj2"

  depends_on macos: ">= :catalina"

  on_arm do
    pkg "mycli-4.0.0-macos-arm64.pkg"
  end

  on_intel do
    pkg "mycli-4.0.0-macos-x86_64.pkg"
  end

  uninstall pkgutil: "com.naga-nandyala.mycli"

  caveats <<~EOS
    MyCLI installs directly to system locations:
      • Executable: /usr/local/bin/mycli
      • Runtime: /usr/local/microsoft/mycli/

    No symlinks or complex path resolution required.

    Basic usage:
      mycli --version
      mycli login
      mycli status

    To uninstall manually:
      sudo rm -f /usr/local/bin/mycli
      sudo rm -rf /usr/local/microsoft/mycli

    For the venv bundle version instead:
      brew install --cask naga-nandyala/mycli-app/mycli-app-venv-pj2
  EOS
end