# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-venv-pj2" do
  version "1.0.0"

  on_arm do
    sha256 "e949eb3f3dee7027c80b8d3d2c7a61fcf486bcf5073762cb46244757235585bc"
    url "https://github.com/naga-nandyala/pj2/releases/download/v#{version}/mycli-1.0.0-macos-arm64.tar.gz"
    binary "bin/mycli", target: "mycli"
  end

  on_intel do
    sha256 "9218fa5b72d3c2ae2c8cb5c12e605d48fbf45e6e54201f71302cee8bcc6f2b4c"
    url "https://github.com/naga-nandyala/pj2/releases/download/v#{version}/mycli-1.0.0-macos-x86_64.tar.gz"
    binary "bin/mycli", target: "mycli"
  end

  name "MyCLI App (venv bundle)"
  desc "Azure-inspired CLI packaged with an embedded Python runtime"
  homepage "https://github.com/naga-nandyala/pj2"

  depends_on macos: ">= :catalina"

  caveats <<~EOS
    Installs a portable Python virtual environment containing all dependencies.

    Basic usage:
      mycli --help
      mycli login
      mycli status

    To install the PyInstaller build instead:
      brew install naga-nandyala/mycli-app/mycli-app
  EOS
end