# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-pkg-pj2" do
  version "2.0.0"

  on_arm do
    sha256 "6f7971ad3a6e98c1d924c6104341ac95f25883e6d55468434235b227a7f1cdd5"
    url "https://github.com/naga-nandyala/pj2/releases/download/v2.0.0/mycli-2.0.0-macos-arm64.pkg"
  end

  on_intel do
    sha256 "211d1d69eb4cb896c879ae2122330e2f3d2d21623083331f67c29a72e918e79e"
    url "https://github.com/naga-nandyala/pj2/releases/download/v2.0.0/mycli-2.0.0-macos-x86_64.pkg"
  end

  name "MyCLI App (PKG Installer)"
  desc "Azure-inspired CLI with native macOS installer"
  homepage "https://github.com/naga-nandyala/pj2"

  depends_on macos: ">= :catalina"

  on_arm do
    pkg "mycli-2.0.0-macos-arm64.pkg"
  end

  on_intel do
    pkg "mycli-2.0.0-macos-x86_64.pkg"
  end

  uninstall pkgutil: "com.naga-nandyala.mycli"

  caveats <<~EOS
    MyCLI installs directly to system locations:
      • Executable: /usr/local/bin/mycli
      • Runtime: /usr/local/libexec/mycli-venv/

    No symlinks or complex path resolution required.

    Basic usage:
      mycli --version
      mycli login
      mycli status

    To uninstall manually:
      sudo rm -f /usr/local/bin/mycli
      sudo rm -rf /usr/local/libexec/mycli-venv

    For the venv bundle version instead:
      brew install --cask naga-nandyala/mycli-app/mycli-app-venv-pj2
  EOS
end