name: Create Self-Signed Certificate (Learning)

on:
    workflow_dispatch: # Manual trigger only

jobs:
    create-cert:
        runs-on: macos-latest

        steps:
            - name: Create self-signed certificate
              run: |
                  echo "=== Creating Self-Signed Certificate ==="

                  # Create temporary directory
                  mkdir -p ~/cert-temp
                  cd ~/cert-temp

                  # Create OpenSSL config for code signing certificate
                  cat > codesign.conf << 'EOF'
                  [req]
                  default_bits = 2048
                  distinguished_name = req_distinguished_name
                  x509_extensions = v3_req
                  prompt = no

                  [req_distinguished_name]
                  C = US
                  ST = State
                  L = City
                  O = MyOrg
                  OU = Development
                  CN = Developer ID Installer: MyOrg (TESTCERT)

                  [v3_req]
                  keyUsage = critical, digitalSignature
                  extendedKeyUsage = critical, codeSigning
                  basicConstraints = critical, CA:FALSE
                  subjectKeyIdentifier = hash
                  EOF

                  # Generate private key
                  openssl genrsa -out private-key.pem 2048

                  # Create self-signed certificate with code signing extensions
                  openssl req -new -x509 -days 365 \
                    -key private-key.pem \
                    -out certificate.pem \
                    -config codesign.conf

                  # Create PKCS12 bundle (.p12) with password
                  CERT_PASSWORD="test123"
                  openssl pkcs12 -export -out certificate.p12 \
                    -inkey private-key.pem \
                    -in certificate.pem \
                    -name "Developer ID Installer: MyOrg (TESTCERT)" \
                    -password pass:$CERT_PASSWORD

                  # Verify P12 contains both certificate and key
                  echo ""
                  echo "=== Verifying P12 bundle ==="
                  openssl pkcs12 -in certificate.p12 -nokeys -passin pass:$CERT_PASSWORD | \
                    openssl x509 -noout -subject -dates
                  echo "✅ Certificate found in P12"

                  # Check if private key is present
                  if openssl pkcs12 -in certificate.p12 -nocerts -passin pass:$CERT_PASSWORD -passout pass:temp123 2>/dev/null | grep -q "PRIVATE KEY"; then
                    echo "✅ Private key found in P12"
                  else
                    echo "❌ Private key NOT found in P12"
                  fi
                  echo ""

                  # Convert to base64 (for GitHub secrets)
                  base64 -i certificate.p12 -o certificate-base64.txt

                  echo ""
                  echo "=== Certificate Created Successfully ==="
                  echo ""
                  echo "Certificate Details:"
                  openssl x509 -in certificate.pem -text -noout | grep -A 2 "Subject:"

                  echo ""
                  echo "=== IMPORTANT: Copy these values to GitHub Secrets ==="
                  echo ""
                  echo "Secret Name: APPLE_SIGNING_CERTIFICATE"
                  echo "Secret Value (base64):"
                  cat certificate-base64.txt
                  echo ""
                  echo "Secret Name: APPLE_CERT_PASSWORD"
                  echo "Secret Value: test123"
                  echo ""

            - name: Test certificate import
              run: |
                  cd ~/cert-temp

                  echo "=== Testing Certificate Import ==="

                  # Create temporary keychain
                  KEYCHAIN="$RUNNER_TEMP/test.keychain"
                  KEYCHAIN_PASSWORD="temp123"
                  CERT_PASSWORD="test123"

                  security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
                  security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
                  security set-keychain-settings -lut 21600 "$KEYCHAIN"

                  # Verify P12 file exists
                  echo "P12 file info:"
                  ls -lh certificate.p12
                  echo ""

                  # Import certificate with -A flag
                  echo "Importing certificate..."
                  security import certificate.p12 -k "$KEYCHAIN" \
                    -P "$CERT_PASSWORD" \
                    -T /usr/bin/productsign \
                    -A

                  echo "Import exit code: $?"
                  echo ""

                  security list-keychains -d user -s "$KEYCHAIN"
                  security set-key-partition-list -S apple-tool:,apple: \
                    -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN"

                  echo ""
                  echo "=== Keychain Contents ==="
                  security dump-keychain "$KEYCHAIN" | grep -A 3 "class:" | head -30
                  echo ""

                  echo "=== Available signing identities (trusted only) ==="
                  security find-identity -v -p codesigning
                  echo ""

                  echo "=== All identities in keychain ==="
                  security find-identity -v
                  echo ""

                  if security find-identity -v | grep -q "Developer ID Installer"; then
                      echo "✅ Certificate imported successfully and can be used for signing!"
                  else
                      echo "⚠️  Certificate imported but may not be recognized for signing"
                  fi

                  # Cleanup
                  security delete-keychain "$KEYCHAIN"

            - name: Display next steps
              run: |
                  echo ""
                  echo "=========================================="
                  echo "=== COPY THE VALUES ABOVE TO GITHUB ====="
                  echo "=========================================="
                  echo ""
                  echo "Next Steps:"
                  echo "1. Scroll up and copy the base64 value (very long string)"
                  echo "2. Go to: https://github.com/${{ github.repository }}/settings/secrets/actions"
                  echo "3. Click 'New repository secret'"
                  echo "4. Add secret: APPLE_SIGNING_CERTIFICATE = <paste base64 value>"
                  echo "5. Add secret: APPLE_CERT_PASSWORD = test123"
                  echo "6. Run the 'pkgsign-build-installer.yml' workflow"
                  echo ""
                  echo "Note: This is a SELF-SIGNED certificate for LEARNING."
                  echo "macOS will still show Gatekeeper warnings."
                  echo "For production, use Apple Developer ID certificate."
                  echo ""

            - name: Save certificate info
              run: |
                  cd ~/cert-temp

                  cat > CERTIFICATE_INFO.txt << 'EOF'
                  Self-Signed Certificate Information
                  ===================================

                  Created: $(date)
                  Valid for: 365 days
                  Password: test123

                  Subject: CN=My Test Installer Certificate

                  GitHub Secrets to Create:
                  -------------------------
                  1. APPLE_SIGNING_CERTIFICATE = <contents of certificate-base64.txt>
                  2. APPLE_CERT_PASSWORD = test123

                  Note: This is a SELF-SIGNED certificate for LEARNING only.
                  macOS will still show Gatekeeper warnings.
                  For production, use Apple Developer ID certificate.

                  Certificate Purpose:
                  -------------------
                  - Learn PKG signing mechanics
                  - Test CI/CD workflows
                  - Understand certificate chains
                  - Practice before spending $99 on Apple Developer Program

                  This certificate is NOT suitable for:
                  ------------------------------------
                  - Public distribution
                  - Production releases
                  - Removing Gatekeeper warnings
                  - Homebrew public taps

                  Next Phase:
                  -----------
                  When ready for production:
                  1. Enroll in Apple Developer Program ($99/year)
                  2. Request Developer ID Installer certificate
                  3. Export and encode to base64
                  4. Replace these GitHub secrets with production values
                  5. Same workflows will automatically use production cert!
                  EOF

            - name: Upload certificate artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: self-signed-certificate-info
                  path: ~/cert-temp/CERTIFICATE_INFO.txt
                  retention-days: 7

            - name: Security reminder
              run: |
                  echo ""
                  echo "⚠️  SECURITY REMINDER ⚠️"
                  echo ""
                  echo "This workflow created a self-signed certificate for LEARNING."
                  echo "The certificate and private key are in the logs above."
                  echo ""
                  echo "For PRODUCTION:"
                  echo "- Use Apple Developer ID certificate"
                  echo "- Never share .p12 files publicly"
                  echo "- Never commit certificates to git"
                  echo "- Store only in GitHub Secrets"
                  echo "- Rotate secrets periodically"
                  echo ""
